version: "3.7"
services:
  redis:
    image: redis
    restart: always
    network_mode: host
    volumes:
      - ./redis_volume/redis-data:/var/lib/redis
      - ./redis_volume/redis.conf:/usr/local/etc/redis/redis.conf
