version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    network_mode: host
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
