version: "3.5"

services:
  pgadmin:
    container_name: pgadmin_only
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
    network_mode: host
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgadmin:
